task-manager ondrejmal
GeorgeFreelanceDeveloper/task-manager pull request #13
Opened 2024-12-29 09:28 UTC by ondrejmal

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper requested changes

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +        ArrayList<String[]> tasks = loadTasks(filePath);
CLEAN-CODE: promennou tasks a scanner prosim nastav jako globalni v ramci tridy, pouzivaji se totiz skoro ve vsech metodach.

```java
 private static String[][] tasks;
 private static Scanner scanner;
```

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +            System.err.println("Problem with loading the file. File not found. Check if the file exists.");
BUG: spatny popis chyby v vyjimce, IOException != vzdy FileNotFound vyjimka. FileNotFoundException je podtrida tridy IOException.

Zdroj: FileNotFoundException

```suggestion
            System.err.println("Failed to load tasks.csv");
```

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +        tasks.add(new String[]{note, date, String.valueOf(status)});
CLEAN-CODE: kdyz se na ten kod divam tak prevadis status na boolean a pak zpatky  na string, tohle bych zrusil.

```suggestion
        tasks.add(new String[]{note, date,statusInput});
```

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +            e.printStackTrace(System.err);
IMPROVE: zde bych pridal skonceni programu s chybovym kodem.

```java
System.exit(1);
```

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +            String command = scanner.nextLine().trim().toLowerCase();
```suggestion
            final String command = scanner.nextLine().trim().toLowerCase();
```

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +        String filePath = "tasks.csv";
CLEAN-CODE: z promenne filePath bych udelal konstantu navrchu v tride.

```
private static final String FILE_PATH = "tasks.csv";
```

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +        ArrayList<String[]> fileTasks = new ArrayList<>();
```suggestion
        final List<String[]> fileTasks = new ArrayList<>();
```

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +                int taskToBeErased = Integer.parseInt(scanner.nextLine());
```suggestion
                final int taskToBeErased = Integer.parseInt(scanner.nextLine());
```

2025-01-01 08:20 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +                String[] removedTask = tasks.remove(taskToBeErased - 1);
```suggestion
                final String[] removedTask = tasks.remove(taskToBeErased - 1);
```

2025-01-04 16:52 UTC, ondrejmal commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +        ArrayList<String[]> tasks = loadTasks(filePath);
opraveno, nevim teda zda jsem to pouzil spravne...

2025-01-04 16:56 UTC, ondrejmal commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +            System.err.println("Problem with loading the file. File not found. Check if the file exists.");
opraveno

2025-01-04 16:59 UTC, ondrejmal commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +            e.printStackTrace(System.err);
opraveno

2025-01-04 17:01 UTC, ondrejmal commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +            String command = scanner.nextLine().trim().toLowerCase();
opraveno

2025-01-04 17:11 UTC, ondrejmal commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +        String filePath = "tasks.csv";
opraveno

2025-01-04 17:26 UTC, ondrejmal commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +                int taskToBeErased = Integer.parseInt(scanner.nextLine());
opraveno

2025-01-04 17:29 UTC, ondrejmal commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +                String[] removedTask = tasks.remove(taskToBeErased - 1);
opraveno

2025-01-04 17:29 UTC, ondrejmal commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +        tasks.add(new String[]{note, date, String.valueOf(status)});
opraveno

2025-01-04 20:58 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/ondrejmal/TaskManager.java
> +        ArrayList<String[]> fileTasks = new ArrayList<>();
ok, tak to tak ted nechejme a priste je lepsi davat obecny typ promenne a do toho davat konkretni implementaci.

2025-01-09 22:02 UTC, merged