Workshop - Task manager
GeorgeFreelanceDeveloper/task-manager pull request #2
Opened 2024-12-22 13:18 UTC by simon8491

2024-12-22 14:06 UTC, GeorgeFreelanceDeveloper requested changes
Zaklad dobry, prosim o upravu dle komentaru.

2024-12-22 14:06 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        String[] options = {"add", "remove", "list", "exit"};
CLEAN-CODE: promennou options bych dal jako kontstantu nahoru ve tride.

`
static final String[] OPTIONS = {"add", "remove", "list", "exit"};
`

2024-12-22 14:06 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            e.printStackTrace(err);
BUG: pokud nejde nacist ukoly, dale pracovat s promennou tasks = null asi nedava smysl a program spadne. Radsi bych zde ukoncil program s kodem -1.

2024-12-22 14:06 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            exit(0);
BUG: kdyz program konci chybou mel by vratit kod -1

2024-12-22 14:06 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        var input = new Scanner(in);
BUG: mit jednu promennou scanner globalne je lepsi nez ji dvakrat vytvaret. navic koukam ze ji ani neuzaviras na konci.

2024-12-22 14:06 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +import static java.lang.System.*;
BUG: tohle neni dobry napad delat, bezne se pouziva System.out.println(), ne out.println() spise to mate nez ze by to bylo uzitecne.

2024-12-22 14:06 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        String[] line = new String[tasks.length];
CLEAN-CODE: pole, kolekce oznacovat mnoznym cislem s (s) na konci

`
line -> lines
`

2024-12-22 14:06 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        Path file = Paths.get("tasks.csv");
CLEAN-CODE: kde je mozne pouzivat nemenne promenne tedy final.

2024-12-22 15:22 UTC, simon8491 reviewed
Opraveno.

2024-12-25 21:09 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            switch (option) {
**Oprava v poradku.**

2024-12-29 15:14 UTC, closed without merging