To-do list workshop project completion
GeorgeFreelanceDeveloper/task-manager pull request #3
Opened 2024-12-22 13:31 UTC by adambrg

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper requested changes
Zaklad dobry, prosim o upravu dle komentaru.

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +import java.util.Arrays;
CLEAN-CODE: odeber prosim z pull-requestu konfiguracni veci z idei.

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        System.out.println(ConsoleColors.RED + "Exiting application..");
BUG: pridat uzavirani scanneru pred ukoncenim programu.

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        File file = new File(fileName);
PERFORMANCE-IMPROVE: v kodu vidim ze dvakrat nacitas soubor, to je z pohledu vykonu ne moc efektivni. lze to udelat najednou.

Inspirace

```
private static void loadTasks() {
        try {
            final var lines = Files.readAllLines(TASK_FILE_PATH);

            tasks = new String[lines.size()][];
            for (int i = 0; i < lines.size(); i++) {
                tasks[i] = lines.get(i).split(", ");
            }
        } catch (IOException e) {
            System.err.println("Failed to load tasks.csv");
            e.printStackTrace(System.err);
        }

    }
```

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            retrieveData();
PERFORMANCE-IPROVE: v kazdem cyklu nacitat znovu data ze souboru nedava smysl, kdyz uz mas jednou ukoly nactene v promenne tasks. Lepsi je tohle provest pouze jednou na zacatku programu.

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        String[] options = {"add", "remove", "list", "exit"};
CLEAN-CODE: promennou options bych vytvoril jako konstantu na zacatku tridy.

```java
static final String[] OPTIONS = {"add", "remove", "list", "exit"};
```

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            String input = scanner.nextLine();
CLEAN-CODE: promenna input se pouziva jenom jednou v switch, proto navrhuji promennou zrusit a nacitani provest primo ve switch + pridat toLowerCase() pro moznost zadat prikaz jakkoli.

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            switch (input) {
CLEAN-CODE: lze pouzit jednodussi konstrukci switche kde neni treba davat na kazdy radek break od javy 14.

Url: https://docs.oracle.com/en/java/javase/17/language/switch-expressions-and-statements.html

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        try (PrintWriter Writer = new PrintWriter(new FileWriter(fileName, true))) {
PERFORMANCE-IMPROVE: ukladat se dle zadani melo az pri ukoncovani aplikace, pri kazdem vlozeni noveho zaznamu pridavat do souboru neni uplne efektivni z pohledu rychlosti.

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            System.err.println("Saving failed.");
IMPROVE: Je lepsi vypsat i cely stack trace pro hledani priciny chyby.

Tedy:

e.printStackTrace(System.err);

2024-12-22 14:22 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +                saveTasksToFile();
BUG: saveTasksToFile() se vola az pri ukoncovani programu.

2025-01-01 16:07 UTC, closed without merging

2025-01-01 16:15 UTC, adambrg commented on src/main/java/org/example/Main.java
> +import java.util.Arrays;
opraveno

2025-01-01 16:15 UTC, adambrg commented on src/main/java/org/example/Main.java
> +        System.out.println(ConsoleColors.RED + "Exiting application..");
opraveno

2025-01-01 16:15 UTC, adambrg commented on src/main/java/org/example/Main.java
> +        File file = new File(fileName);
opraveno

2025-01-01 16:15 UTC, adambrg commented on src/main/java/org/example/Main.java
> +        String[] options = {"add", "remove", "list", "exit"};
opraveno

2025-01-01 16:15 UTC, adambrg commented on src/main/java/org/example/Main.java
> +            String input = scanner.nextLine();
opraveno

2025-01-01 16:15 UTC, adambrg commented on src/main/java/org/example/Main.java
> +            switch (input) {
opraveno

2025-01-01 16:15 UTC, adambrg commented on src/main/java/org/example/Main.java
> +            System.err.println("Saving failed.");
opraveno

2025-01-01 16:15 UTC, adambrg commented on src/main/java/org/example/Main.java
> +                saveTasksToFile();
opraveno