init
GeorgeFreelanceDeveloper/task-manager pull request #4
Opened 2024-12-22 13:38 UTC by ZvedamRance

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper requested changes
Ahoj Petre,

Dobre zpracovany ukol, nasel jsem tam par veci typu CLEAN-CODE, BUG a IMPROVE, prosim koukni na to a pak kdyz to opravis tak dej k memu komentari text: Opraveno nebo pripadne se zeptej.

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +    public static void main(String[] args) {
CLEAN-CODE: main metodu bych dal jako prvni metodu nahoru, at se program dobre cte.

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +    static final String[] OPTIONS = {"add", "remove", "list", "exit"};
CLEAN-CODE: globalni promenne prosim dat pristupne pouze z tridy TaskManager, pridat private pred promenne, plus novy radek mezi definici globalnich promennych a metod.
```suggestion
    final static File file = new File("tasks.csv");
    final static String[][] tasks;
    final static final String[] OPTIONS = {"add", "remove", "list", "exit"};
    
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        menuButtons();
CLEAN-CODE: medodu menuButtons() bych zrusil a tento kod dal primo do metody main() s tim ze switch bych dal dale do nekonecne smycky while(true) a ukonceni by probihalo po zadani "exit" volby v metode exit() kde se zavola System.exit(0).

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        String input = scanner.nextLine();
CLEAN-CODE: promenne v metodach pokud to jde davat nemenne tedy final, vyhnes se omylu ze do promenne neco dvakrat prirazujes.
```suggestion
        final String input = scanner.nextLine();
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        Scanner scanner = new Scanner(System.in);
BUG: promennou scanner pouzivas v ruznych metodach, nastav ji jako globalni na zacatku tridy. Navic koukam ze scanner neuzaviras coz je spatne, jak ho das jako globalni tak v metode exit() zavolej scanner.close()

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        switch (input) {
CLEAN-CODE: prosim zjednodus pomoci switch expression. 

Zdroj: https://docs.oracle.com/en/java/javase/17/language/switch-expressions-and-statements.html

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        Scanner scanner = new Scanner(System.in);
BUG: neuzavreny scanner, pouzij globalni scanner viz komentar vyse.

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        String name = scanner.nextLine();
```suggestion
        final String name = scanner.nextLine();
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        String date = scanner.nextLine();
```suggestion
        final String date = scanner.nextLine();
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        String bool = scanner.nextLine();
CLEAN-CODE: konkretnejsi pojmenovani isDone

```suggestion
        final String isDone = scanner.nextLine();
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        showMainMenu();
IMPROVE: odstranit radek, bude zobrazeno v ramci nekonecne smycky v main metode.
```suggestion
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        showMainMenu();
IMPROVE: odstranit radek, bude zobrazeno v ramci nekonecne smycky v main metode.
```suggestion
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        showMainMenu();
IMPROVE: odstranit radek, bude zobrazeno v ramci nekonecne smycky v main metode.

```suggestion
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        showMainMenu();
CLEAN-CODE: lepsi struktura.

```suggestion
 private static void list() {
        System.out.println(ConsoleColors.PURPLE + "Id:[Note, Date, IsImportant ]");
        System.out.println(ConsoleColors.RESET + "-----------------");
        for (int i= 0; i < tasks.length; i++) {
            System.out.println( i + ":"  + Arrays.toString(tasks[i]));
        }
    }
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +    public static void retrievingData () {
CLEAN-CODE: lepsi popis metody.

```suggestion
    public static void loadTasks() {
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        ArrayList<String> list = new ArrayList<>();
CLEAN-CODE: lepsi pojmenovani promenne + nemennost pridat.

```suggestion
        final ArrayList<String> lines = new ArrayList<>();
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +            e.printStackTrace();
BUG: spatne zpracovana vyjimka.

```suggestion
            System.err.println("Failed to load tasks.csv");
            e.printStackTrace(System.err);
            System.exit(1);
```

2024-12-26 10:54 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/TaskManager.java
> +        try (Writer writer = new FileWriter(file)) {
CLEAN-CODE: ukladani ukolu bych dal do podmetody saveTasks() a tu pak volal v ramci exit().

2025-01-01 09:26 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +    public static void main(String[] args) {
opraveno

2025-01-01 09:26 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +    static final String[] OPTIONS = {"add", "remove", "list", "exit"};
opraveno

2025-01-01 09:26 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +        menuButtons();
opraveno

2025-01-01 09:26 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +        String input = scanner.nextLine();
opraveno

2025-01-01 09:26 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +        Scanner scanner = new Scanner(System.in);
opraveno

2025-01-01 09:26 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +        showMainMenu();
opraveno

2025-01-01 09:27 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +    public static void retrievingData () {
opraveno

2025-01-01 09:27 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +        ArrayList<String> list = new ArrayList<>();
opraveno

2025-01-01 09:27 UTC, ZvedamRance commented on src/main/java/org/example/TaskManager.java
> +            e.printStackTrace();
opraveno

2025-01-01 09:39 UTC, GeorgeFreelanceDeveloper requested changes

2025-01-01 09:39 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/zvedamrance/TaskManager.java
> +        int number = -1;
IMPROVE: zjednodusil bych tuto konstrukci a promennou number bych zrusil s tim ze mazani tasku bude pred break prikazem.

2025-01-01 09:39 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/zvedamrance/TaskManager.java
> +                number = Integer.parseInt(input);
CLEAN-CODE: lepsi pojmenovani jedna se o index v poli, number je dosti obecne.

```suggestion
                final int index = Integer.parseInt(input);
```

2025-01-01 09:39 UTC, GeorgeFreelanceDeveloper commented on src/main/java/cz/student/zvedamrance/TaskManager.java
> +        }
IMPROVE: dle me by nacteni pole ukolu slo jeste zjednodusit.

```suggestion
        for (int i = 0; i < lines.size(); i++) {
            final var task = lines.get(i).split(",");
            tasks[i] = task;
        }
```

2025-01-01 10:20 UTC, ZvedamRance commented on src/main/java/cz/student/zvedamrance/TaskManager.java
> +        int number = -1;
opraveno

2025-01-01 10:20 UTC, ZvedamRance commented on src/main/java/cz/student/zvedamrance/TaskManager.java
> +                number = Integer.parseInt(input);
opraveno

2025-01-01 10:20 UTC, ZvedamRance commented on src/main/java/cz/student/zvedamrance/TaskManager.java
> +        }
opraveno

2025-01-01 13:19 UTC, GeorgeFreelanceDeveloper approved these changes

2025-01-01 15:27 UTC, merged