initial commit
GeorgeFreelanceDeveloper/task-manager pull request #5
Opened 2024-12-22 14:13 UTC by ondrejmal

2024-12-22 15:52 UTC, GeorgeFreelanceDeveloper requested changes

2024-12-23 22:20 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +        while (!exit) {
opraveno

2024-12-23 22:20 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +            switch (command) {
zmena provedena

2024-12-23 22:21 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +        if (!date.matches("\\d{4}-\\d{2}-\\d{2}")){
opraveno

2024-12-23 22:23 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +        if (!date.matches("\\d{4}-\\d{2}-\\d{2}")){
jen kdyz jsem tady zmenil promené na final, tak mi to hodilo chybu: java: cannot assign a value to final variable note, co to je prosim tě?

2024-12-23 22:23 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +        if (!date.matches("\\d{4}-\\d{2}-\\d{2}")){
takze v tom co jsem poslal je to bez final (plati u note, date a statusInput)

2024-12-23 22:23 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +        System.out.println("Current tasks:");
opraveno

2024-12-23 22:24 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +                System.out.println("Invalid input. Please insert valid row number.");
opraveno

2024-12-23 22:24 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +        StringBuilder sb = new StringBuilder();
opraveno

2024-12-23 22:27 UTC, ondrejmal commented on src/main/java/org/example/Main.java
> +    public static void terminationOfTheProgram(ArrayList<String[]> fileTasks, String filePath) {
dal jsem to jako programExit, snad v pohode, casto se zasoustredim na neco jineho a pak to zapomenu, jaky je presny pokyn, zbytek je jak jsi chtel, kdyby bylo potreba, tak to predelam

2024-12-29 09:11 UTC, closed without merging

2025-01-01 08:21 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        if (!date.matches("\\d{4}-\\d{2}-\\d{2}")){
Nastavit final lze pouze u promennych ktere pak dale nemenis, coz napriklad pri tom cteni vstupu pri vytvareni tasku neplati.