workshop Kocábek
GeorgeFreelanceDeveloper/task-manager pull request #6
Opened 2024-12-22 15:40 UTC by JanKocabek

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper requested changes
Ahoj Honzo,

Dobre zpracovany ukol, nasel jsem tam par veci typu CLEAN-CODE, BUG a IMPROVE, prosim koukni na to a pak kdyz to opravis tak dej k memu komentari text: Opraveno nebo pripadne se zeptej.

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        boolean isEnd = false;//flag for ending main loop
CLEAN-CODE: prehlednejsi by bylo while(true) a pak pri zadani "exit" zavolavot exit() metodu ktera:

```java
saveTask();
scanner.close();
System.exit(0);
```

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +    private static Scanner scan;
CLEAN-CODE: lepsi pojmenovani promenne je primo scanner je to vice popisne.
```suggestion
    private static Scanner scanner;
```

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            task = tasks[i];
CLEAN-CODE: zjednos to pomoci foreeach cyklu.

```suggestion
        for (var task : tasks) {
```

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        task[1] = " %s".formatted(dateChecker());//because space after comma
CLEAN-CODE: lepsi pojmenovani loadAndCheckDate()
```suggestion
        task[1] = " %s".formatted(loadAndCheckDate());//because space after comma
```

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +    }
IMPROVE: zjednoduseny a prehlednejsi zapis:

```suggestion
private static String loadAndCheckDate() {
  while (true) {
    try {
      final var today = LocalDate.now();
      final var input = scan.nextLine();
      final var date = LocalDate.parse(input);
      if (!date.isBefore(today)) { // date must be at least today if so loop end
        return input;
      }
      System.out.printf(
          "%sThis date already was!!%s\n", RED_BOLD_BRIGHT, RESET);
      System.out.printf("\n%sWrite date which is at least %sToday:%s ",
          BLUE_BOLD_BRIGHT, RED_BOLD_BRIGHT, RESET);
    } catch (DateTimeParseException e) {
      System.out.printf("%sInvalid date format!! %s\n", RED_BOLD_BRIGHT, RESET);
      System.out.printf("\n%sWrite date in the format %sYYY-MM-DD%s:%s ",
          BLUE_BOLD_BRIGHT, YELLOW_BOLD_BRIGHT, BLUE_BOLD_BRIGHT, RESET);
    }
  }
}
```

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +    private static void saveTask() {
CLEAN-CODE: pri ukladani poli nebo kolekci proste kde je vice veci tak pouzivat mnozne cislo v nazvu metody.

```suggestion
    private static void saveTasks() {
```

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        if (Files.exists(pathFile)) {
BUG: pokud soubor neexistuje tak se vytvori, prosim odsranit zaobalujici podminku.

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            final var data = new StringBuilder();
CLEAN-CODE: lepsi pojmenovani promenne.

```suggestion
            final var sb= new StringBuilder();
```

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            }
IMPROVE: vytvoreni finalniho retezce pro ulozeni do souboru lze zjednodusit.

```suggestion
 for (var task : tasks) {
            sb.append(String.join(", ", task));
            sb.append(System.lineSeparator());
        }
```

2024-12-26 10:30 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +                throw new RuntimeException(e);
BUG: nezpracovani vyjimky

```suggestion
            System.err.println("Failed to save tasks.csv");
            e.printStackTrace(System.err);
            System.exit(1);
```

2024-12-26 12:16 UTC, JanKocabek commented on src/main/java/org/example/Main.java
> +            task = tasks[i];
není dobrý nápad podle mně - Já používám "i" ve for cyklu pro výpis čísla  úkolu , takže bych musel pak zase zvlášť tvořit porměnnou

2024-12-26 14:26 UTC, JanKocabek commented on src/main/java/org/example/Main.java
> +            final var data = new StringBuilder();
myslel jsem že je lepší aby nazev byl jasný a smysluplný.?

2024-12-26 14:26 UTC, JanKocabek commented on src/main/java/org/example/Main.java
> +    }
chápu  mít return ve smyčce a  ale mám dotaz: proč mít definici proměných ve smyččce, myslel jsem že je lepší je definovat vždy mimo smyčku aby se při každém volání smyčky netvořili znova ale jenom se do nich uložili nové hodnoty.
chápu že tady se ideálně bude volat jednou maximálně +- třikrát ale i tak , nebo je to je z hlediska paměti a rychlosti jedno, že se proměnné tvoří pokaždé znova?

2024-12-26 14:52 UTC, JanKocabek commented on src/main/java/org/example/Main.java
> +            }
tady se omlouvám, ale toto zjednoduseni nelze máš tam chybu.
toto rozbije csv soubor protoze to udela toto: "popis souboru, novy radek, dastum, novy radek atd..
ja jsem oddelil ten posledni append "true/false" za tu smycku proto  ze predtim kdyz jsem mel uvnitr jeden append a za smyckou pouze lineseparator tak to sice fungovalo
ale v soboru to dělalo  value1,value2,value3,
a podle standartu
za posledni hodnotou neni comma
https://en.wikipedia.org/wiki/Comma-separated_values
takže proto ve smyčce proběhne jenom hodnota1 a 2 a třetí se přidá za smyčkou uz bez ,
a přidá se lineseparator

2024-12-26 15:21 UTC, closed without merging

2024-12-27 09:12 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            final var data = new StringBuilder();
sb je zkratka pro stringBuilder, lze pouzit i dlouhy nazev stringBuilder.

2024-12-27 09:13 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            task = tasks[i];
Aha tohle jsem prehledl, tak to tak nechej.