Added my files for a code review
GeorgeFreelanceDeveloper/task-manager pull request #7
Opened 2024-12-22 15:46 UTC by richard808code

2024-12-26 09:55 UTC, GeorgeFreelanceDeveloper requested changes
Ahoj Richarde,

Dobre zpracovany ukol, nasel jsem tam par veci typu CLEAN-CODE a IMPROVE, prosim koukni na to a pak kdyz to opravis tak dej k memu komentari text: Opraveno nebo pripadne se zeptej.

2024-12-26 09:55 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +    static final String[] OPTIONS = {"add", "remove", "list", "exit"};
CLEAN-CODE: prosim u konstanty OPTIONS pridej taky ze je pristupna jen ve tride Main pridanim private. O objektove orientovanem programovani se budeme vice ucit v lednu.

```suggestion
    private static final String[] OPTIONS = {"add", "remove", "list", "exit"};
```

2024-12-26 09:55 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +                case "add" -> tasks = addTask();
CLEAN-CODE: pokud je promenna 'tasks' globalni je lepsi ukol ulozit do pole primo  v metode addTask() 
```suggestion
                case "add" -> addTask();
```

2024-12-26 09:55 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +                case "remove" -> tasks = removeTask();
CLEAN-CODE: pokud je promenna 'tasks' globalni neni treba vracet hodnotu z funkce, ale pracovat s promennou tasks primo.

```suggestion
                case "remove" -> removeTask();
```

2024-12-26 09:55 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +                case "exit" -> exitTasks();
CLEAN-CODE: lepsi pojmenovani metody.
```suggestion
                case "exit" -> exit();
```

2024-12-26 09:55 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +            System.exit(-1);
IMPROVE: u ocekavanych vyjimek jsem zjistil ze se ma vracet cislo 1, omlouvam se pokud jsem ti poradil tu -1.

Nula => Vše v pořádku
Pozitivní => Něco, co jsem očekával, ze by se mohlo potenciálně pokazit, se pokazilo (špatný příkazový řádek, nelze najít soubor, nelze se připojit k serveru)
Negativní => Něco, co jsem vůbec nečekal, se pokazilo (systémová chyba - neočekávaná výjimka - externě vynucené ukončení, např. kill -9)

Zdroj: https://stackoverflow.com/questions/2434592/difference-in-system-exit0-system-exit-1-system-exit1-in-java

2024-12-26 09:55 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +        while (done == null) {
CLEAN-CODE: validacni smycku bych udelal vsude podobne a jednodussi na pochopeni je while(true).

```suggestion
        while (true) {
```

2024-12-26 09:55 UTC, GeorgeFreelanceDeveloper commented on src/main/java/org/example/Main.java
> +                scanner.nextLine();
```suggestion
                scanner.nextLine();
                break;
```

2024-12-27 08:53 UTC, closed without merging

2024-12-27 09:01 UTC, richard808code commented on src/main/java/org/example/Main.java
> +    static final String[] OPTIONS = {"add", "remove", "list", "exit"};
Opraveno.

2024-12-27 09:03 UTC, richard808code commented on src/main/java/org/example/Main.java
> +                case "add" -> tasks = addTask();
Opraveno.

2024-12-27 09:03 UTC, richard808code commented on src/main/java/org/example/Main.java
> +                case "remove" -> tasks = removeTask();
Opraveno.

2024-12-27 09:04 UTC, richard808code commented on src/main/java/org/example/Main.java
> +                case "exit" -> exitTasks();
Opraveno.

2024-12-27 09:05 UTC, richard808code commented on src/main/java/org/example/Main.java
> +            System.exit(-1);
Opraveno.

2024-12-27 09:08 UTC, richard808code commented on src/main/java/org/example/Main.java
> +        while (done == null) {
Opraveno.